### ISSUE TITLE
When any other, not included, vox model is loaded.

### ISSUE THREAD

**Issue by LanceJZ** [procfxgen/BVoxelViewer#1]
It stops on line 96 of MagicaVoxelLoader.bf: uint32 chunkName = _stream.Read<uint32>();
This happens on all vox models I've tried, both my own and included with last version of MagicalVoxel, only the two you included work.
If I change the code to while (_stream.Position < _stream.Length - 3) (Not -2) it works on other models, but without a material (All black) on the Doom vox model that came with MagicaVoxel.

**Comment by fxgenstudio** [comment]
It's fixed.
